---
- name: Add Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Add Jenkins repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins and Java
  apt:
    name:
      - openjdk-17-jre
      - jenkins
    state: present

- name: Configure Jenkins to use custom port
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JENKINS_PORT='
    line: 'JENKINS_PORT=8080'  # Change this port to whatever you want
    state: present

- name: Ensure Jenkins service is running and enabled
  systemd:
    name: jenkins
    enabled: yes
    state: restarted
