---
- name: Create necessary groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - awscli
    - terraform
    - kubectl
    - trivy

- name: Add Jenkins user to groups
  user:
    name: jenkins
    groups: docker,awscli,terraform,kubectl,trivy
    append: yes

- name: Set permissions for Docker
  file:
    path: /usr/bin/docker
    group: docker
    mode: '0755'

- name: Set permissions for AWS CLI
  file:
    path: /usr/local/bin/aws
    group: awscli
    mode: '0755'

- name: Set permissions for Terraform
  file:
    path: /usr/bin/terraform
    group: terraform
    mode: '0755'

- name: Set permissions for kubectl
  file:
    path: /usr/local/bin/kubectl
    group: kubectl
    mode: '0755'

- name: Set permissions for Trivy
  file:
    path: /usr/bin/trivy
    group: trivy
    mode: '0755'

