---
- name: Download kubectl
  get_url:
    url: https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
