---
- name: Download Trivy
  get_url:
    url: https://github.com/aquasecurity/trivy/releases/download/v0.42.0/trivy_0.42.0_Linux-64bit.deb
    dest: /tmp/trivy.deb

- name: Install Trivy
  apt:
    deb: /tmp/trivy.deb
    