apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: library
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: ahmedalaa14/flask-app-mini
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: python-app-pv
          mountPath: /app
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
      volumes:
      - name: python-app-pv
        persistentVolumeClaim:
          claimName: python-app-pvc