apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-app-pvc
  namespace: library
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      storageClassName: ""  # This is the default storage class