- name: install and configure Jenkins on EC2 instance
  hosts: jenkins-ec2
  become: true
  roles:
    - common
    - docker
    - awscli
    - kubernetes
    - terraform
    - trivy
    - jenkins
    - permissions